### ISSUE TITLE
new std/http@0.107 API support

### ISSUE THREAD

**Issue by v1rtl** [timonson/gentleRpc#9]
New std/http API uses native HTTP and is very different from previous std/http

would be cool to support it

I'll submit a PR for this

**Comment by timonson** [comment]
Hi, I already made these necessary changes on my local device. Additionally I fixed some things and made some improvements. I will push a PR in the coming days where I would welcome you to contribute. Please wait for this PR before you make further changes. The reason why I have not done this yet is because I wanted to wait for the deno authors to merge their new Websockets API as well.

**Comment by timonson** [comment]
Here is the PR https://github.com/timonson/gentle_rpc/pull/10

**Comment by v1rtl** [comment]
oh nice, thx!
